-- =====================================================================
-- ANÁLISIS DE BASE DE DATOS - ESTRUCTURA ACTUAL
-- Creado: 14 de Enero 2026
-- Propósito: Entender la estructura para guardar procesos de pedidos
-- =====================================================================

-- 1. INFORMACIÓN DE TABLAS PRINCIPALES
SELECT 
    TABLE_NAME,
    TABLE_TYPE,
    TABLE_COLLATION,
    TABLE_ROWS
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME;

-- 2. ESTRUCTURA DE TABLA: pedidos
DESCRIBE pedidos;
SHOW CREATE TABLE pedidos\G

-- 3. ESTRUCTURA DE TABLA: pedido_items
DESCRIBE pedido_items;
SHOW CREATE TABLE pedido_items\G

-- 4. ESTRUCTURA DE TABLA: pedido_prendas (si existe)
DESCRIBE pedido_prendas;
SHOW CREATE TABLE pedido_prendas\G

-- 5. ESTRUCTURA DE TABLA: reflectivo (para ver patrón existente)
DESCRIBE reflectivo;
SHOW CREATE TABLE reflectivo\G

-- 6. ESTRUCTURA DE TABLA: estampado (si existe)
DESCRIBE estampado;
SHOW CREATE TABLE estampado\G

-- 7. VER TODAS LAS COLUMNAS DE TODAS LAS TABLAS
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    COLUMN_TYPE,
    IS_NULLABLE,
    COLUMN_KEY,
    EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME, ORDINAL_POSITION;

-- 8. VER RELACIONES FORÁNEAS
SELECT 
    CONSTRAINT_NAME,
    TABLE_NAME,
    COLUMN_NAME,
    REFERENCED_TABLE_NAME,
    REFERENCED_COLUMN_NAME
FROM INFORMATION_SCHEMA.KEY_COLUMN_USAGE
WHERE TABLE_SCHEMA = DATABASE()
AND REFERENCED_TABLE_NAME IS NOT NULL;

-- 9. VER ÍNDICES
SELECT 
    TABLE_NAME,
    INDEX_NAME,
    COLUMN_NAME,
    SEQ_IN_INDEX
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = DATABASE()
ORDER BY TABLE_NAME, INDEX_NAME;

-- 10. EJEMPLO: VER ESTRUCTURA COMPLETA DE UNA FILA DE PEDIDO
SELECT * FROM pedidos LIMIT 1\G
SELECT * FROM pedido_items LIMIT 1\G
